// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkihtvercgsguqhxcsry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraWh0dmVyY2dzZ3VxaHhjc3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzc4NTEsImV4cCI6MjA3Mzg1Mzg1MX0.WzS3YD3b2aLyEUGqNQuX_IBuX894uHGt507fkzfa_Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});